//import API from '../../API';

export const USER_CHANGE_INPUT_VALUE_NAME = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_NAME';
export const USER_CHANGE_INPUT_VALUE_PHONE = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_PHONE';
export const USER_CHANGE_INPUT_VALUE_EMAIL = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_EMAIL';
export const USER_CHANGE_INPUT_VALUE_INCOME = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_INCOME';
export const USER_CHANGE_INPUT_VALUE_FAMILY = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_FAMILY';
export const USER_CHANGE_INPUT_VALUE_RESIDENCE = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_RESIDENCE';
export const USER_CHANGE_INPUT_VALUE_CRIMINAL_RECORD = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_RECORD';
export const USER_CHANGE_INPUT_VALUE_HEALTH = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_HEALTH';
export const USER_CHANGE_INPUT_VALUE_CHAR_JOB = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_CHAR_JOB';
export const USER_CHANGE_INPUT_VALUE_CHAR_RES = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_CHAR_RES';
export const USER_CHANGE_INPUT_VALUE_BIGRAPHY = '[INFORMATION_ABOUT_CHILDREN_FORM] USER_CHANGE_INPUT_VALUE_BIOGRAPHY';

// ACTIONS
export const userChangeInputValueName = value => ({
  type: USER_CHANGE_INPUT_VALUE_NAME,
  payload: value
})

export const userChangeInputValuePhone = value => ({
  type: USER_CHANGE_INPUT_VALUE_PHONE,
  payload: value
})

export const userChangeInputValueEmail = value => ({
  type: USER_CHANGE_INPUT_VALUE_EMAIL,
  payload: value
})

// ACTIONS //


// THUNKS

export const userChangeInputValueNameThunk = value => dispatch => {
  dispatch(userChangeInputValueName(value));
}

export const userChangeInputValuePhoneThunk = value => dispatch => {
  dispatch(userChangeInputValuePhone(value))
}

export const userChangeInputValueEmailThunk = value => dispatch => {
  dispatch(userChangeInputValueEmail(value))
}

// THUNKS //